#\!/bin/bash
# Fix USB device in Docker container

echo "🔍 Diagnostic USB pour Docker"
echo "=============================="
echo ""

echo "ÉTAPE 1: Vérifier sur l'HÔTE (serveur Linux)"
echo "============================================="
echo ""
echo "Exécutez ces commandes sur le SERVEUR (pas dans le conteneur):"
echo ""
echo "# 1. Vérifier que le module USB est détecté"
echo "lsusb | grep 1a86"
echo ""
echo "# 2. Vérifier les ports série disponibles"
echo "ls -l /dev/ttyUSB*"
echo ""
echo "# Vous devriez voir:"
echo "# crw-rw---- 1 root dialout ... /dev/ttyUSB0"
echo ""

echo "ÉTAPE 2: Créer la règle udev (sur l'HÔTE)"
echo "=========================================="
echo ""
echo "sudo nano /etc/udev/rules.d/99-lcus-relay.rules"
echo ""
echo "Copiez cette ligne:"
echo '────────────────────────────────────────────────────'
echo 'SUBSYSTEM=="tty", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="7523", SYMLINK+="lcus_relay", MODE="0666", GROUP="dialout"'
echo '────────────────────────────────────────────────────'
echo ""
echo "Puis recharger:"
echo "sudo udevadm control --reload-rules"
echo "sudo udevadm trigger"
echo ""
echo "Vérifier que /dev/lcus_relay existe:"
echo "ls -l /dev/lcus_relay"
echo ""

echo "ÉTAPE 3: Configurer docker-compose.yml"
echo "======================================="
echo ""
echo "Ajoutez dans votre docker-compose.yml:"
echo ""
echo "services:"
echo "  homeassistant:"
echo "    devices:"
echo "      - /dev/lcus_relay:/dev/lcus_relay"
echo "    # OU si la règle udev ne fonctionne pas:"
echo "    # - /dev/ttyUSB0:/dev/ttyUSB0"
echo ""

echo "ÉTAPE 4: Redémarrer le conteneur"
echo "================================="
echo ""
echo "# Docker Compose:"
echo "docker-compose down && docker-compose up -d"
echo ""
echo "# Docker Swarm:"
echo "docker stack rm hass"
echo "sleep 10"
echo "docker stack deploy -c docker-compose.yml hass"
echo ""

echo "ÉTAPE 5: Vérifier dans le conteneur"
echo "===================================="
echo ""
echo "# Vérifier que le device est visible"
echo "docker exec homeassistant ls -l /dev/lcus_relay"
echo ""
echo "# Tester la connexion"
echo 'docker exec homeassistant python3 -c "import serial; s=serial.Serial('\''/dev/lcus_relay'\'', 9600); print('\''✓ OK'\''); s.close()"'
echo ""

echo "────────────────────────────────────────────────────"
echo "⚠️  ALTERNATIVE RAPIDE (si la règle udev ne fonctionne pas)"
echo "────────────────────────────────────────────────────"
echo ""
echo "Sur l'HÔTE:"
echo "sudo chmod 666 /dev/ttyUSB0"
echo ""
echo "Dans docker-compose.yml:"
echo "  devices:"
echo "    - /dev/ttyUSB0:/dev/ttyUSB0"
echo ""
echo "Puis redémarrer le conteneur."
echo ""
